import { Metadata } from "next"

export const metadata : Metadata= {
  title: {
    default:"Next Js by INOSUKE-SAMA",
    template:"%s | INOSUKE-SAMA"
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style={{
          backgroundColor:"lightblue",
          padding:"1rem"
        }}>
          <p>Header</p>
        </header>
        {children}
        <footer>
          <p style={{
            backgroundColor:"ghostwhite",
            padding:"1rem"
          }}>Foooter</p>
        </footer>
      </body>
    </html>
  )
}
